### ISSUE TITLE
Doesn't work for Xamarin debug.keystore with blank password 

### ISSUE THREAD

**Issue by tinonetic** [funambol/android-sms-hash-generator#2]
For Xamarin, the default debug keystore used to sign the app uses a blank password.

The python script does not support it

**Comment by tinonetic** [comment]
Ok, just realised I was wrong about the Xamarin **debug.keystore** having no password

It does have a password, it's **_android_**

Secondly the underlying JDK **_keytool_** utility used to export the certificate expects a non-blank password. 

> storepass must be at least 6 characters long. It must be provided to all commands that access the keystore contents. For such commands, if a -storepass option is not provided at the command line, the user is prompted for it.

http://docs.oracle.com/javase/1.3/docs/tooldocs/win32/keytool.html

Works as expected!

Thanks for the tool!

**Comment by francescomapelli** [comment]
thank you @tinonetic ! :)
